cxxopts::values Namespace Reference
Namespaces
namespace detail
namespace parser_tool
Classes
class abstract_value
class standard_value
class standard_value< bool >
struct type_is_container
struct type_is_container< std::vector< T > >
Functions
template<typename R , typename T >
void checked_negate (R &, T &&, const std::string &text, std::false_type)
template<typename R , typename T >
void checked_negate (R &r, T &&t, const std::string &, std::true_type)
template<typename T >
void integer_parser (const std::string &text, T &value)
void parse_value (const std::string &text, bool &value)
void parse_value (const std::string &text, char &c)
void parse_value (const std::string &text, std::string &value)
template<typename T >
void parse_value (const std::string &text, std::vector< T > &value)
template<typename T , typename std::enable_if< std::is_integral< T >::value >::type * = nullptr>
void parse_value (const std::string &text, T &value)
template<typename T >
void stringstream_parser (const std::string &text, T &value)
Function Documentation
checked_negate() [1/2]
template<typename R , typename T >
void cxxopts::values::checked_negate (R & , T && , const std::string & text, std::false_type)
Definition at line 859 of file cxxopts.hpp.
        {
            throw_or_mimic<argument_incorrect_type>(text);
        }
checked_negate() [2/2]
template<typename R , typename T >
void cxxopts::values::checked_negate (R & r, T && t, const std::string & , std::true_type)
Definition at line 849 of file cxxopts.hpp.
        {
            // if we got to here, then `t` is a positive number that fits into
            // `R`. So to avoid MSVC C4146, we first cast it to `R`.
            // See https://github.com/jarro2783/cxxopts/issues/62 for more details.
            r = static_cast<R>(-static_cast<R>(t-1)-1);
        }
integer_parser()
template<typename T >
void cxxopts::values::integer_parser (const std::string & text, T & value)
Definition at line 866 of file cxxopts.hpp.
        {
            parser_tool::IntegerDesc int_desc = parser_tool::SplitInteger(text);
            using US = typename std::make_unsigned<T>::type;
            constexpr bool is_signed = std::numeric_limits<T>::is_signed;
            const bool negative = int_desc.negative.length() > 0;
            const uint8_t base = int_desc.base.length() > 0 ? 16 : 10;
            const std::string & value_match = int_desc.value;
            US result = 0;
            for (char ch : value_match)
            {
                US digit = 0;
                if (ch >= '0' && ch <= '9')
                {
                    digit = static_cast<US>(ch - '0');
                }
                else if (base == 16 && ch >= 'a' && ch <= 'f')
                {
                    digit = static_cast<US>(ch - 'a' + 10);
                }
                else if (base == 16 && ch >= 'A' && ch <= 'F')
                {
                    digit = static_cast<US>(ch - 'A' + 10);
                }
                else
                {
                    throw_or_mimic<argument_incorrect_type>(text);
                }
                const US next = static_cast<US>(result * base + digit);
                if (result > next)
                {
                    throw_or_mimic<argument_incorrect_type>(text);
                }
                result = next;
            }
            detail::check_signed_range<T>(negative, result, text);
            if (negative)
            {
                checked_negate<T>(value, result, text, std::integral_constant<bool, is_signed>());
            }
            else
            {
                value = static_cast<T>(result);
            }
        }
References cxxopts::values::parser_tool::IntegerDesc::base, cxxopts::values::parser_tool::IntegerDesc::negative, cxxopts::values::parser_tool::SplitInteger(), cxxopts::values::parser_tool::IntegerDesc::value, and cxxopts::value().
Referenced by parse_value().
parse_value() [1/5]
void cxxopts::values::parse_value (const std::string & text, bool & value) [inline]
Definition at line 941 of file cxxopts.hpp.
        {
            if (parser_tool::IsTrueText(text))
            {
                value = true;
                return;
            }
            if (parser_tool::IsFalseText(text))
            {
                value = false;
                return;
            }
            throw_or_mimic<argument_incorrect_type>(text);
        }
References cxxopts::values::parser_tool::IsFalseText(), cxxopts::values::parser_tool::IsTrueText(), and cxxopts::value().
parse_value() [2/5]
void cxxopts::values::parse_value (const std::string & text, char & c) [inline]
Definition at line 1007 of file cxxopts.hpp.
        {
            if (text.length() != 1)
            {
                throw_or_mimic<argument_incorrect_type>(text);
            }
            c = text[0];
        }
parse_value() [3/5]
void cxxopts::values::parse_value (const std::string & text, std::string & value) [inline]
Definition at line 960 of file cxxopts.hpp.
        {
            value = text;
        }
References cxxopts::value().
parse_value() [4/5]
template<typename T >
void cxxopts::values::parse_value (const std::string & text, std::vector< T > & value)
Definition at line 978 of file cxxopts.hpp.
        {
            if (text.empty()) {
                T v;
                parse_value(text, v);
                value.emplace_back(std::move(v));
                return;
            }
            std::stringstream in(text);
            std::string token;
            while(!in.eof() && std::getline(in, token, CXXOPTS_VECTOR_DELIMITER)) {
                T v;
                parse_value(token, v);
                value.emplace_back(std::move(v));
            }
        }
References CXXOPTS_VECTOR_DELIMITER, parse_value(), and cxxopts::value().
parse_value() [5/5]
template<typename T , typename std::enable_if< std::is_integral< T >::value >::type * = nullptr>
void cxxopts::values::parse_value (const std::string & text, T & value)
Definition at line 934 of file cxxopts.hpp.
        {
            integer_parser(text, value);
        }
References integer_parser(), and cxxopts::value().
Referenced by cxxopts::KeyValue::as(), cxxopts::values::abstract_value< T >::parse(), and parse_value().
stringstream_parser()
template<typename T >
void cxxopts::values::stringstream_parser (const std::string & text, T & value)
Definition at line 922 of file cxxopts.hpp.
        {
            std::stringstream in(text);
            in >> value;
            if (!in) {
                throw_or_mimic<argument_incorrect_type>(text);
            }
        }
References cxxopts::value().