cxxopts::values::parser_tool Namespace Reference
Classes
struct ArguDesc
struct IntegerDesc
Functions
bool IsFalseText (const std::string &text)
bool IsTrueText (const std::string &text)
ArguDesc ParseArgument (const char *arg, bool &matched)
IntegerDesc SplitInteger (const std::string &text)
std::pair< std::string, std::string > SplitSwitchDef (const std::string &text)
Function Documentation
IsFalseText()
bool cxxopts::values::parser_tool::IsFalseText (const std::string & text) [inline]
Definition at line 755 of file cxxopts.hpp.
            {
                std::smatch result;
                std::regex_match(text, result, falsy_pattern);
                return !result.empty();
            }
Referenced by cxxopts::values::parse_value().
IsTrueText()
bool cxxopts::values::parser_tool::IsTrueText (const std::string & text) [inline]
Definition at line 748 of file cxxopts.hpp.
            {
                std::smatch result;
                std::regex_match(text, result, truthy_pattern);
                return !result.empty();
            }
Referenced by cxxopts::values::parse_value().
ParseArgument()
ArguDesc cxxopts::values::parser_tool::ParseArgument (const char * arg, bool & matched) [inline]
Definition at line 777 of file cxxopts.hpp.
            {
                std::match_results<const char*> result;
                std::regex_match(arg, result, option_matcher);
                matched = !result.empty();
                ArguDesc argu_desc;
                if (matched) {
                    argu_desc.arg_name = result[1].str();
                    argu_desc.set_value = result[2].length() > 0;
                    argu_desc.value = result[3].str();
                    if (result[4].length() > 0)
                    {
                        argu_desc.grouping = true;
                        argu_desc.arg_name = result[4].str();
                    }
                }
                return argu_desc;
            }
References cxxopts::values::parser_tool::ArguDesc::arg_name, cxxopts::values::parser_tool::ArguDesc::grouping, cxxopts::values::parser_tool::ArguDesc::set_value, and cxxopts::values::parser_tool::ArguDesc::value.
Referenced by cxxopts::OptionParser::parse().
SplitInteger()
IntegerDesc cxxopts::values::parser_tool::SplitInteger (const std::string & text) [inline]
Definition at line 723 of file cxxopts.hpp.
            {
                std::smatch match;
                std::regex_match(text, match, integer_pattern);
                if (match.length() == 0)
                {
                    throw_or_mimic<argument_incorrect_type>(text);
                }
                IntegerDesc desc;
                desc.negative = match[1];
                desc.base = match[2];
                desc.value = match[3];
                if (match.length(4) > 0)
                {
                    desc.base = match[5];
                    desc.value = "0";
                    return desc;
                }
                return desc;
            }
References cxxopts::values::parser_tool::IntegerDesc::base, cxxopts::values::parser_tool::IntegerDesc::negative, and cxxopts::values::parser_tool::IntegerDesc::value.
Referenced by cxxopts::values::integer_parser().
SplitSwitchDef()
std::pair< std::string, std::string > cxxopts::values::parser_tool::SplitSwitchDef (const std::string & text) [inline]
Definition at line 762 of file cxxopts.hpp.
            {
                std::match_results<const char*> result;
                std::regex_match(text.c_str(), result, option_specifier);
                if (result.empty())
                {
                    throw_or_mimic<invalid_option_format_error>(text);
                }
                const std::string& short_sw = result[2];
                const std::string& long_sw = result[3];
                return std::pair<std::string, std::string>(short_sw, long_sw);
            }
Referenced by cxxopts::OptionAdder::operator()().