cxxopts Namespace Reference
Namespaces
namespace values
Classes
class argument_incorrect_type
struct HelpGroupDetails
struct HelpOptionDetails
class invalid_option_format_error
class KeyValue
class missing_argument_exception
struct Option
class option_exists_error
class option_has_no_value_exception
class option_not_exists_exception
class option_not_has_argument_exception
class option_not_present_exception
class option_required_exception
class option_requires_argument_exception
class option_syntax_exception
class OptionAdder
class OptionDetails
class OptionException
class OptionParseException
class OptionParser
class Options
class OptionSpecException
class OptionValue
class ParseResult
class Value
Typedefs
using NameHashMap = std::unordered_map< std::string, size_t >
using OptionMap = std::unordered_map< std::string, std::shared_ptr< OptionDetails > >
using ParsedHashMap = std::unordered_map< size_t, OptionValue >
using PositionalList = std::vector< std::string >
using PositionalListIterator = PositionalList::const_iterator
using String = std::string
Functions
bool empty (const std::string &s)
String & stringAppend (String &s, const String &a)
template<typename Iterator >
String & stringAppend (String &s, Iterator begin, Iterator end)
String & stringAppend (String &s, size_t n, char c)
size_t stringLength (const String &s)
template<typename T >
void throw_or_mimic (const std::string &text)
template<typename T >
T toLocalString (T &&t)
template<typename T >
std::string toUTF8String (T &&t)
template<typename T >
std::shared_ptr< Value > value ()
template<typename T >
std::shared_ptr< Value > value (T &t)
Variables
xx xx xx xx xx xx xx xx xx
struct {
 uint8_t cxxopts::major
 uint8_t cxxopts::minor
 uint8_t cxxopts::patch
} version
Typedef Documentation
NameHashMap
using cxxopts::NameHashMap = typedef std::unordered_map<std::string, size_t>
Definition at line 1453 of file cxxopts.hpp.
OptionMap
using cxxopts::OptionMap = typedef std::unordered_map<std::string, std::shared_ptr<OptionDetails> >
Definition at line 1649 of file cxxopts.hpp.
ParsedHashMap
using cxxopts::ParsedHashMap = typedef std::unordered_map<size_t, OptionValue>
Definition at line 1452 of file cxxopts.hpp.
PositionalList
using cxxopts::PositionalList = typedef std::vector<std::string>
Definition at line 1650 of file cxxopts.hpp.
PositionalListIterator
using cxxopts::PositionalListIterator = typedef PositionalList::const_iterator
Definition at line 1651 of file cxxopts.hpp.
String
using cxxopts::String = typedef std::string
Definition at line 248 of file cxxopts.hpp.
Function Documentation
empty()
bool cxxopts::empty (const std::string & s) [inline]
Definition at line 294 of file cxxopts.hpp.
    {
        return s.empty();
    }
Referenced by cxxopts::Options::generate_group_help().
stringAppend() [1/3]
String & cxxopts::stringAppend (String & s, const String & a) [inline]
Definition at line 266 of file cxxopts.hpp.
    {
        return s.append(a);
    }
stringAppend() [2/3]
template<typename Iterator >
String & cxxopts::stringAppend (String & s, Iterator begin, Iterator end)
Definition at line 280 of file cxxopts.hpp.
    {
        return s.append(begin, end);
    }
stringAppend() [3/3]
String & cxxopts::stringAppend (String & s, size_t n, char c) [inline]
Definition at line 273 of file cxxopts.hpp.
    {
        return s.append(n, c);
    }
stringLength()
size_t cxxopts::stringLength (const String & s) [inline]
Definition at line 259 of file cxxopts.hpp.
    {
        return s.length();
    }
Referenced by cxxopts::Options::help_one_group().
throw_or_mimic()
template<typename T >
void cxxopts::throw_or_mimic (const std::string & text)
Definition at line 530 of file cxxopts.hpp.
    {
        static_assert(std::is_base_of<std::exception, T>::value,
                      "throw_or_mimic only works on std::exception and "
                      "deriving classes");
#ifndef CXXOPTS_NO_EXCEPTIONS
        // If CXXOPTS_NO_EXCEPTIONS is not defined, just throw
        throw T{text};
#else
        // Otherwise manually instantiate the exception, print what() to stderr,
    // and exit
    T exception{text};
    std::cerr << exception.what() << std::endl;
    std::exit(EXIT_FAILURE);
#endif
    }
References value().
toLocalString()
template<typename T >
T cxxopts::toLocalString (T && t)
Definition at line 252 of file cxxopts.hpp.
    {
        return std::forward<T>(t);
    }
Referenced by cxxopts::Options::add_option(), cxxopts::Options::help(), and cxxopts::Options::help_one_group().
toUTF8String()
template<typename T >
std::string cxxopts::toUTF8String (T && t)
Definition at line 287 of file cxxopts.hpp.
    {
        return std::forward<T>(t);
    }
Referenced by cxxopts::Options::help().
value() [1/2]
template<typename T >
std::shared_ptr< Value > cxxopts::value ()
Definition at line 1212 of file cxxopts.hpp.
    {
        return std::make_shared<values::standard_value<T>>();
    }
Referenced by cxxopts::Options::add_option(), cxxopts::values::detail::check_signed_range(), cxxopts::OptionParser::checked_parse_arg(), cxxopts::values::abstract_value< T >::default_value(), cxxopts::values::abstract_value< T >::implicit_value(), cxxopts::values::integer_parser(), cxxopts::OptionAdder::operator()(), cxxopts::OptionParser::parse(), cxxopts::OptionParser::parse_option(), cxxopts::values::parse_value(), and cxxopts::values::stringstream_parser().
value() [2/2]
template<typename T >
std::shared_ptr< Value > cxxopts::value (T & t)
Definition at line 1219 of file cxxopts.hpp.
    {
        return std::make_shared<values::standard_value<T>>(&t);
    }
Referenced by cxxopts::values::abstract_value< T >::is_boolean(), and throw_or_mimic().
Variable Documentation
major
uint8_t cxxopts::major
Definition at line 83 of file cxxopts.hpp.
minor
uint8_t cxxopts::minor
Definition at line 83 of file cxxopts.hpp.
patch
uint8_t cxxopts::patch
Definition at line 83 of file cxxopts.hpp.
constexpr struct { ... } cxxopts::version [static]
Initial value:
= {
            CXXOPTS__VERSION_MAJOR,
            CXXOPTS__VERSION_MINOR,
            CXXOPTS__VERSION_PATCH
    }