StringMatch::details::STree Class Reference
Compressed suffix tree Ukkonen's algorithm.
#include <Ukkonen.h>
Classes
struct AlgoPos
struct STreeNode
Public Member Functions
STree (const std::string_view &ptext)
size_t find (const std::string &pattern)
Private Member Functions
void build_tree ()
void finalize ()
long long get_link (long long v)
AlgoPos go (AlgoPos st, long long l, long long r)
void setSuffixIndexByDFS (size_t n, size_t labelHeight)
size_t size ()
long long split (AlgoPos st)
char text (size_t pos)
void tree_extend (long long pos)
Private Attributes
vector< STreeNode > nodes
AlgoPos ptr = {0, 0}
const std::string_view text_view
Static Private Attributes
static const char ender = '\1'
Detailed Description
Compressed suffix tree Ukkonen's algorithm.
Definition at line 22 of file Ukkonen.h.
Constructor & Destructor Documentation
STree()
StringMatch::details::STree::STree (const std::string_view & ptext) [explicit]
Definition at line 113 of file Ukkonen.cpp.
                                            : text_view(ptext) {
        build_tree();
        finalize();
    }
References build_tree(), and finalize().
Member Function Documentation
build_tree()
void StringMatch::details::STree::build_tree () [private]
Definition at line 90 of file Ukkonen.cpp.
                           {
        nodes.emplace_back(0, 0, -1);
        for (long long i = 0; i < size(); ++i)
            tree_extend(i);
    }
References nodes, size(), and tree_extend().
Referenced by STree().
finalize()
void StringMatch::details::STree::finalize () [private]
Definition at line 109 of file Ukkonen.cpp.
                         {
        setSuffixIndexByDFS(0, 0);
    }
References setSuffixIndexByDFS().
Referenced by STree().
find()
size_t StringMatch::details::STree::find (const std::string & pattern)
Definition at line 118 of file Ukkonen.cpp.
                                               {
        AlgoPos st = {0, 0};
        size_t l = 0;
        const size_t r = pattern.size();
        while (l < pattern.size()) {
            if (st.pos == nodes[st.v].len()) {
                st = AlgoPos(nodes[st.v].get(pattern[l]), 0);
                if (st.v == -1)
                    break;
            } else {
                if (text(nodes[st.v].start + st.pos) != pattern[l]) {
                    return -1;
                }
                if (r - l < nodes[st.v].len() - st.pos) {
                    st = AlgoPos(st.v, st.pos + r - l);
                    break;
                }
                l += nodes[st.v].len() - st.pos;
                st.pos = nodes[st.v].len();
            }
        }
        if (st.v == -1)
            return -1;
        return nodes[st.v].suffixIndex;
    }
References nodes, StringMatch::details::STree::AlgoPos::pos, text(), and StringMatch::details::STree::AlgoPos::v.
Referenced by StringMatch::SingleSearcher::getEntrances().
get_link()
long long StringMatch::details::STree::get_link (long long v) [private]
Definition at line 63 of file Ukkonen.cpp.
                                             {
        if (nodes[v].suffLink != -1) return nodes[v].suffLink;
        if (nodes[v].parent == -1) return 0;
        long long to = get_link(nodes[v].parent);
        return nodes[v].suffLink = split(go({to, nodes[to].len()},
                                            nodes[v].start + (nodes[v].parent == 0),
                                            nodes[v].end));
    }
References get_link(), go(), nodes, and split().
Referenced by get_link(), and tree_extend().
go()
STree::AlgoPos StringMatch::details::STree::go (AlgoPos st, long long l, long long r) [private]
Definition at line 32 of file Ukkonen.cpp.
                                                               {
        while (l < r)
            if (st.pos == nodes[st.v].len()) {
                st = AlgoPos(nodes[st.v].get(text(l)), 0);
                if (st.v == -1) return st;
            } else {
                if (text(nodes[st.v].start + st.pos) != text(l))
                    return AlgoPos(-1, -1);
                if (r - l < nodes[st.v].len() - st.pos)
                    return AlgoPos(st.v, st.pos + r - l);
                l += nodes[st.v].len() - st.pos;
                st.pos = nodes[st.v].len();
            }
        return st;
    }
References nodes, StringMatch::details::STree::AlgoPos::pos, text(), and StringMatch::details::STree::AlgoPos::v.
Referenced by get_link(), and tree_extend().
setSuffixIndexByDFS()
void StringMatch::details::STree::setSuffixIndexByDFS (size_t n, size_t labelHeight) [private]
Definition at line 96 of file Ukkonen.cpp.
                                                                {
        size_t minSuffLen = size();
        for (auto i: nodes[n].next) {
            setSuffixIndexByDFS(i.second, labelHeight + nodes[i.second].len());
            minSuffLen = std::min(minSuffLen, (size_t) nodes[i.second].suffixIndex);
        }
        if (nodes[n].next.empty())
            nodes[n].suffixIndex = size() - labelHeight;
        else {
            nodes[n].suffixIndex = minSuffLen;
        }
    }
References nodes, setSuffixIndexByDFS(), and size().
Referenced by finalize(), and setSuffixIndexByDFS().
size()
size_t StringMatch::details::STree::size () [inline], [private]
Definition at line 23 of file Ukkonen.cpp.
                       {
        return text_view.size() + 1;
    }
References text_view.
Referenced by build_tree(), setSuffixIndexByDFS(), and tree_extend().
split()
long long StringMatch::details::STree::split (STree::AlgoPos st) [private]
Definition at line 48 of file Ukkonen.cpp.
                                          {
        if (st.pos == nodes[st.v].len())
            return st.v;
        if (st.pos == 0)
            return nodes[st.v].parent;
        STreeNode v = nodes[st.v];
        long long id = nodes.size();
        nodes.emplace_back(v.start, v.start + st.pos, v.parent);
        nodes[v.parent].get(text(v.start)) = id;
        nodes[id].get(text(v.start + st.pos)) = st.v;
        nodes[st.v].parent = id;
        nodes[st.v].start += st.pos;
        return id;
    }
References nodes, StringMatch::details::STree::STreeNode::parent, StringMatch::details::STree::AlgoPos::pos, StringMatch::details::STree::STreeNode::start, text(), and StringMatch::details::STree::AlgoPos::v.
Referenced by get_link(), and tree_extend().
text()
char StringMatch::details::STree::text (size_t pos) [inline], [private]
Definition at line 27 of file Ukkonen.cpp.
                               {
        return pos == text_view.size() ? ender : text_view[pos];
    }
References ender, and text_view.
Referenced by find(), go(), split(), and tree_extend().
tree_extend()
void StringMatch::details::STree::tree_extend (long long pos) [private]
Definition at line 72 of file Ukkonen.cpp.
                                             {
        for (;;) {
            auto nptr = go(ptr, pos, pos + 1);
            if (nptr.v != -1) {
                ptr = nptr;
                return;
            }
            long long mid = split(ptr);
            long long leaf = nodes.size();
            nodes.emplace_back(pos, size(), mid);
            nodes[mid].get(text(pos)) = leaf;
            ptr.v = get_link(mid);
            ptr.pos = nodes[ptr.v].len();
            if (!mid) break;
        }
    }
References get_link(), go(), nodes, StringMatch::details::STree::AlgoPos::pos, ptr, size(), split(), text(), and StringMatch::details::STree::AlgoPos::v.
Referenced by build_tree().
Member Data Documentation
ender
const char StringMatch::details::STree::ender = '\1' [static], [private]
Definition at line 28 of file Ukkonen.h.
Referenced by text().
nodes
vector<STreeNode> StringMatch::details::STree::nodes [private]
Definition at line 69 of file Ukkonen.h.
Referenced by build_tree(), find(), get_link(), go(), setSuffixIndexByDFS(), split(), and tree_extend().
ptr
AlgoPos StringMatch::details::STree::ptr = {0, 0} [private]
Definition at line 68 of file Ukkonen.h.
Referenced by tree_extend().
text_view
const std::string_view StringMatch::details::STree::text_view [private]
Definition at line 70 of file Ukkonen.h.
Referenced by size(), and text().
The documentation for this class was generated from the following files:
src/core/details/Ukkonen.h
src/core/details/Ukkonen.cpp