StringMatch::details::KMP Class Reference
Knuth-Morris-Pratt algorithm for searching pattern in text.
#include <KMP.h>
Public Member Functions
KMP (const std::string_view &text)
std::vector< size_t > getEntrances (const std::string &pat)
Private Member Functions
std::vector< size_t > computeLPSArray (const std::string &pat)
Private Attributes
const std::string_view text
Detailed Description
Knuth-Morris-Pratt algorithm for searching pattern in text.
Definition at line 14 of file KMP.h.
Constructor & Destructor Documentation
KMP()
StringMatch::details::KMP::KMP (const std::string_view & text) [explicit]
Definition at line 30 of file KMP.cpp.
: text(text) {}
Member Function Documentation
computeLPSArray()
std::vector< size_t > StringMatch::details::KMP::computeLPSArray (const std::string & pat) [private]
Definition at line 8 of file KMP.cpp.
                                                               {
        std::vector<size_t> lps(pat.size());
        lps[0] = 0;
        size_t len = 0, i = 1;
        while (i < pat.size()) {
            if (pat[i] == pat[len]) {
                len++;
                lps[i] = len;
                i++;
            } else {
                if (len != 0) {
                    len = lps[len - 1];
                } else // if (len == 0)
                {
                    lps[i] = 0;
                    i++;
                }
            }
        }
        return lps;
    }
Referenced by getEntrances().
getEntrances()
std::vector< size_t > StringMatch::details::KMP::getEntrances (const std::string & pat)
Definition at line 32 of file KMP.cpp.
                                                            {
        std::vector<size_t> entrances;
        auto M = pat.size(), N = text.size();
        auto lps = computeLPSArray(pat);
        size_t i = 0;
        size_t j = 0;
        while (i < N) {
            if (pat[j] == text[i]) {
                j++;
                i++;
            }
            if (j == M) {
                entrances.push_back(i - j);
                j = lps[j - 1];
            } else if (i < N && pat[j] != text[i]) {
                if (j != 0)
                    j = lps[j - 1];
                else
                    i = i + 1;
            }
        }
        return entrances;
    }
References computeLPSArray(), and text.
Referenced by StringMatch::GeneralSearcher::getEntrances().
Member Data Documentation
text
const std::string_view StringMatch::details::KMP::text [private]
Definition at line 22 of file KMP.h.
Referenced by getEntrances().
The documentation for this class was generated from the following files:
src/core/details/KMP.h
src/core/details/KMP.cpp