StringMatch::StringMatcher Class Reference
Optimized pattern search in string.
#include <StringMatcher.h>
Public Member Functions
StringMatcher (const std::string_view &text, bool first=false)
~StringMatcher () override
std::vector< size_t > getEntrances (const std::string &pattern) override
Private Attributes
MatcherInterface * matcher = nullptr
bool single
const std::string_view & text
Detailed Description
Optimized pattern search in string.
Automatically selects the best algorithm
Definition at line 13 of file StringMatcher.h.
Constructor & Destructor Documentation
StringMatcher()
StringMatch::StringMatcher::StringMatcher (const std::string_view & text, bool first = false) [explicit]
Definition at line 11 of file StringMatcher.cpp.
            : text(text), single(single) {
        if (single) {
            matcher = new SingleSearcher(text);
        }
    }
References matcher, single, and text.
 StringMatcher()
StringMatch::StringMatcher::~StringMatcher () [override]
Definition at line 38 of file StringMatcher.cpp.
                                  {
        delete matcher;
    }
References matcher.
Member Function Documentation
getEntrances()
std::vector< size_t > StringMatch::StringMatcher::getEntrances (const std::string & pattern) [override], [virtual]
Implements StringMatch::MatcherInterface.
Definition at line 18 of file StringMatcher.cpp.
                                                                          {
        if (single) {
            return matcher->getEntrances(pattern);
        }
        switch (pattern.size()) {
            case 1:
            case 2:
            case 4:
            case 8: {
                SmallSearcher searcher(text);
                return searcher.getEntrances(pattern);
            }
            default: {
                GeneralSearcher searcher(text);
                return searcher.getEntrances(pattern);
            }
        }
    }
References StringMatch::GeneralSearcher::getEntrances(), StringMatch::SmallSearcher::getEntrances(), StringMatch::MatcherInterface::getEntrances(), matcher, single, and text.
Referenced by StringMatch::LargeMatcher::getEntrances().
Member Data Documentation
matcher
MatcherInterface* StringMatch::StringMatcher::matcher = nullptr [private]
Definition at line 24 of file StringMatcher.h.
Referenced by StringMatcher(), ~StringMatcher(), and getEntrances().
single
bool StringMatch::StringMatcher::single [private]
Definition at line 23 of file StringMatcher.h.
Referenced by StringMatcher(), and getEntrances().
text
const std::string_view& StringMatch::StringMatcher::text [private]
Definition at line 22 of file StringMatcher.h.
Referenced by StringMatcher(), and getEntrances().
The documentation for this class was generated from the following files:
src/core/StringMatcher.h
src/core/StringMatcher.cpp