cxxopts::Options Class Reference
#include <cxxopts.hpp>
Public Member Functions
Options (std::string program, std::string help_string=``)
void add_option (const std::string &group, const Option &option)
void add_option (const std::string &group, const std::string &s, const std::string &l, std::string desc, const std::shared_ptr< const Value > &value, std::string arg_help)
void add_options (const std::string &group, std::initializer_list< Option > options)
OptionAdder add_options (std::string group=``)
Options & allow_unrecognised_options ()
Options & custom_help (std::string help_text)
const HelpGroupDetails & group_help (const std::string &group) const
std::vector< std::string > groups () const
std::string help (const std::vector< std::string > &groups={}) const
ParseResult parse (int argc, const char *const *argv)
template<typename Iterator >
void parse_positional (Iterator begin, Iterator end)
void parse_positional (std::initializer_list< std::string > options)
void parse_positional (std::string option)
void parse_positional (std::vector< std::string > options)
Options & positional_help (std::string help_text)
const std::string & program () const
Options & set_tab_expansion (bool expansion=true)
Options & set_width (size_t width)
Options & show_positional_help ()
Private Member Functions
void add_one_option (const std::string &option, const std::shared_ptr< OptionDetails > &details)
void generate_all_groups_help (String &result) const
void generate_group_help (String &result, const std::vector< std::string > &groups) const
String help_one_group (const std::string &group) const
Private Attributes
bool m_allow_unrecognised
std::string m_custom_help {}
std::map< std::string, HelpGroupDetails > m_help {}
String m_help_string {}
std::shared_ptr< OptionMap > m_options
std::vector< std::string > m_positional {}
std::string m_positional_help {}
std::unordered_set< std::string > m_positional_set {}
std::string m_program {}
bool m_show_positional
bool m_tab_expansion
size_t m_width
Detailed Description
Definition at line 1711 of file cxxopts.hpp.
Constructor & Destructor Documentation
Options()
cxxopts::Options::Options (std::string program, std::string help_string = ``) [inline], [explicit]
Definition at line 1715 of file cxxopts.hpp.
                : m_program(std::move(program))
                , m_help_string(toLocalString(std::move(help_string)))
                , m_custom_help("[OPTION...]")
                , m_positional_help("positional parameters")
                , m_show_positional(false)
                , m_allow_unrecognised(false)
                , m_width(76)
                , m_tab_expansion(false)
                , m_options(std::make_shared<OptionMap>())
        {
        }
Member Function Documentation
add_one_option()
void cxxopts::Options::add_one_option (const std::string & option, const std::shared_ptr< OptionDetails > & details) [inline], [private]
Definition at line 2519 of file cxxopts.hpp.
    {
        auto in = m_options->emplace(option, details);
        if (!in.second)
        {
            throw_or_mimic<option_exists_error>(option);
        }
    }
References m_options.
Referenced by add_option().
add_option() [1/2]
void cxxopts::Options::add_option (const std::string & group, const Option & option) [inline]
Definition at line 2472 of file cxxopts.hpp.
    {
        add_options(group, {option});
    }
References add_options().
add_option() [2/2]
void cxxopts::Options::add_option (const std::string & group, const std::string & s, const std::string & l, std::string desc, const std::shared_ptr< const Value > & value, std::string arg_help) [inline]
Definition at line 2483 of file cxxopts.hpp.
    {
        auto stringDesc = toLocalString(std::move(desc));
        auto option = std::make_shared<OptionDetails>(s, l, stringDesc, value);
        if (!s.empty())
        {
            add_one_option(s, option);
        }
        if (!l.empty())
        {
            add_one_option(l, option);
        }
        //add the help details
        auto& options = m_help[group];
        options.options.emplace_back(HelpOptionDetails{s, l, stringDesc,
                                                       value->has_default(), value->get_default_value(),
                                                       value->has_implicit(), value->get_implicit_value(),
                                                       std::move(arg_help),
                                                       value->is_container(),
                                                       value->is_boolean()});
    }
References add_one_option(), m_help, cxxopts::toLocalString(), and cxxopts::value().
add_options() [1/2]
void cxxopts::Options::add_options (const std::string & group, std::initializer_list< Option > options) [inline]
Definition at line 2078 of file cxxopts.hpp.
    {
        OptionAdder option_adder(*this, group);
        for (const auto &option: options)
        {
            option_adder(option.opts_, option.desc_, option.value_, option.arg_help_);
        }
    }
add_options() [2/2]
OptionAdder cxxopts::Options::add_options (std::string group = ``) [inline]
Definition at line 2093 of file cxxopts.hpp.
    {
        return OptionAdder(*this, std::move(group));
    }
Referenced by add_option().
allow_unrecognised_options()
Options & cxxopts::Options::allow_unrecognised_options () [inline]
Definition at line 1750 of file cxxopts.hpp.
        {
            m_allow_unrecognised = true;
            return *this;
        }
References m_allow_unrecognised.
custom_help()
Options & cxxopts::Options::custom_help (std::string help_text) [inline]
Definition at line 1736 of file cxxopts.hpp.
        {
            m_custom_help = std::move(help_text);
            return *this;
        }
References m_custom_help.
generate_all_groups_help()
void cxxopts::Options::generate_all_groups_help (String & result) const [inline], [private]
Definition at line 2634 of file cxxopts.hpp.
    {
        std::vector<std::string> all_groups;
        std::transform(
                m_help.begin(),
                m_help.end(),
                std::back_inserter(all_groups),
                [] (const std::map<std::string, HelpGroupDetails>::value_type& group)
                {
                    return group.first;
                }
        );
        generate_group_help(result, all_groups);
    }
References generate_group_help(), and m_help.
Referenced by help().
generate_group_help()
void cxxopts::Options::generate_group_help (String & result, const std::vector< std::string > & groups) const [inline], [private]
Definition at line 2611 of file cxxopts.hpp.
    {
        for (size_t i = 0; i != print_groups.size(); ++i)
        {
            const String& group_help_text = help_one_group(print_groups[i]);
            if (empty(group_help_text))
            {
                continue;
            }
            result += group_help_text;
            if (i < print_groups.size() - 1)
            {
                result += '\n';
            }
        }
    }
References cxxopts::empty(), and help_one_group().
Referenced by generate_all_groups_help(), and help().
group_help()
const HelpGroupDetails & cxxopts::Options::group_help (const std::string & group) const [inline]
Definition at line 2697 of file cxxopts.hpp.
    {
        return m_help.at(group);
    }
References m_help.
groups()
std::vector< std::string > cxxopts::Options::groups () const [inline]
Definition at line 2678 of file cxxopts.hpp.
    {
        std::vector<std::string> g;
        std::transform(
                m_help.begin(),
                m_help.end(),
                std::back_inserter(g),
                [] (const std::map<std::string, HelpGroupDetails>::value_type& pair)
                {
                    return pair.first;
                }
        );
        return g;
    }
References m_help.
help()
std::string cxxopts::Options::help (const std::vector< std::string > & groups = {}) const [inline]
Definition at line 2653 of file cxxopts.hpp.
    {
        String result = m_help_string + "\nUsage:\n " +
                        toLocalString(m_program) + " " + toLocalString(m_custom_help);
        if (!m_positional.empty() && !m_positional_help.empty()) {
            result += " " + toLocalString(m_positional_help);
        }
        result += "\n\n";
        if (help_groups.empty())
        {
            generate_all_groups_help(result);
        }
        else
        {
            generate_group_help(result, help_groups);
        }
        return toUTF8String(result);
    }
References generate_all_groups_help(), generate_group_help(), m_custom_help, m_help_string, m_positional, m_positional_help, m_program, cxxopts::toLocalString(), and cxxopts::toUTF8String().
help_one_group()
String cxxopts::Options::help_one_group (const std::string & group) const [inline], [private]
Definition at line 2535 of file cxxopts.hpp.
    {
        using OptionHelp = std::vector<std::pair<String, String>>;
        auto group = m_help.find(g);
        if (group == m_help.end())
        {
            return "";
        }
        OptionHelp format;
        size_t longest = 0;
        String result;
        if (!g.empty())
        {
            result += toLocalString(" " + g + " options:\n");
        }
        for (const auto& o : group->second.options)
        {
            if (m_positional_set.find(o.l) != m_positional_set.end() &&
                !m_show_positional)
            {
                continue;
            }
            auto s = format_option(o);
            longest = (std::max)(longest, stringLength(s));
            format.push_back(std::make_pair(s, String()));
        }
        longest = (std::min)(longest, OPTION_LONGEST);
        //widest allowed description -- min 10 chars for helptext/line
        size_t allowed = 10;
        if (m_width > allowed + longest + OPTION_DESC_GAP)
        {
            allowed = m_width - longest - OPTION_DESC_GAP;
        }
        auto fiter = format.begin();
        for (const auto& o : group->second.options)
        {
            if (m_positional_set.find(o.l) != m_positional_set.end() &&
                !m_show_positional)
            {
                continue;
            }
            auto d = format_description(o, longest + OPTION_DESC_GAP, allowed, m_tab_expansion);
            result += fiter->first;
            if (stringLength(fiter->first) > longest)
            {
                result += '\n';
                result += toLocalString(std::string(longest + OPTION_DESC_GAP, ' '));
            }
            else
            {
                result += toLocalString(std::string(longest + OPTION_DESC_GAP -
                                                    stringLength(fiter->first),
                                                    ' '));
            }
            result += d;
            result += '\n';
            ++fiter;
        }
        return result;
    }
References m_help, m_positional_set, m_show_positional, m_tab_expansion, m_width, cxxopts::stringLength(), and cxxopts::toLocalString().
Referenced by generate_group_help().
parse()
ParseResult cxxopts::Options::parse (int argc, const char *const * argv) [inline]
Definition at line 2278 of file cxxopts.hpp.
    {
        OptionParser parser(*m_options, m_positional, m_allow_unrecognised);
        return parser.parse(argc, argv);
    }
References m_allow_unrecognised, m_options, m_positional, and cxxopts::OptionParser::parse().
parse_positional() [1/4]
template<typename Iterator >
void cxxopts::Options::parse_positional (Iterator begin, Iterator end) [inline]
Definition at line 1813 of file cxxopts.hpp.
                                                       {
            parse_positional(std::vector<std::string>{begin, end});
        }
References parse_positional().
parse_positional() [2/4]
void cxxopts::Options::parse_positional (std::initializer_list< std::string > options) [inline]
Definition at line 2271 of file cxxopts.hpp.
    {
        parse_positional(std::vector<std::string>(options));
    }
References parse_positional().
parse_positional() [3/4]
void cxxopts::Options::parse_positional (std::string option) [inline]
Definition at line 2255 of file cxxopts.hpp.
    {
        parse_positional(std::vector<std::string>{std::move(option)});
    }
References parse_positional().
Referenced by parse_positional().
parse_positional() [4/4]
void cxxopts::Options::parse_positional (std::vector< std::string > options) [inline]
Definition at line 2262 of file cxxopts.hpp.
    {
        m_positional = std::move(options);
        m_positional_set.insert(m_positional.begin(), m_positional.end());
    }
References m_positional, and m_positional_set.
positional_help()
Options & cxxopts::Options::positional_help (std::string help_text) [inline]
Definition at line 1729 of file cxxopts.hpp.
        {
            m_positional_help = std::move(help_text);
            return *this;
        }
References m_positional_help.
program()
const std::string & cxxopts::Options::program () const [inline]
Definition at line 1826 of file cxxopts.hpp.
        {
            return m_program;
        }
References m_program.
set_tab_expansion()
Options & cxxopts::Options::set_tab_expansion (bool expansion = true) [inline]
Definition at line 1764 of file cxxopts.hpp.
        {
            m_tab_expansion = expansion;
            return *this;
        }
References m_tab_expansion.
set_width()
Options & cxxopts::Options::set_width (size_t width) [inline]
Definition at line 1757 of file cxxopts.hpp.
        {
            m_width = width;
            return *this;
        }
References m_width.
show_positional_help()
Options & cxxopts::Options::show_positional_help () [inline]
Definition at line 1743 of file cxxopts.hpp.
        {
            m_show_positional = true;
            return *this;
        }
References m_show_positional.
Member Data Documentation
m_allow_unrecognised
bool cxxopts::Options::m_allow_unrecognised [private]
Definition at line 1858 of file cxxopts.hpp.
Referenced by allow_unrecognised_options(), and parse().
m_custom_help
std::string cxxopts::Options::m_custom_help {} [private]
Definition at line 1855 of file cxxopts.hpp.
Referenced by custom_help(), and help().
m_help
std::map<std::string, HelpGroupDetails> cxxopts::Options::m_help {} [private]
Definition at line 1867 of file cxxopts.hpp.
Referenced by add_option(), generate_all_groups_help(), group_help(), groups(), and help_one_group().
m_help_string
String cxxopts::Options::m_help_string {} [private]
Definition at line 1854 of file cxxopts.hpp.
Referenced by help().
m_options
std::shared_ptr<OptionMap> cxxopts::Options::m_options [private]
Definition at line 1862 of file cxxopts.hpp.
Referenced by add_one_option(), and parse().
m_positional
std::vector<std::string> cxxopts::Options::m_positional {} [private]
Definition at line 1863 of file cxxopts.hpp.
Referenced by help(), parse(), and parse_positional().
m_positional_help
std::string cxxopts::Options::m_positional_help {} [private]
Definition at line 1856 of file cxxopts.hpp.
Referenced by help(), and positional_help().
m_positional_set
std::unordered_set<std::string> cxxopts::Options::m_positional_set {} [private]
Definition at line 1864 of file cxxopts.hpp.
Referenced by help_one_group(), and parse_positional().
m_program
std::string cxxopts::Options::m_program {} [private]
Definition at line 1853 of file cxxopts.hpp.
Referenced by help(), and program().
m_show_positional
bool cxxopts::Options::m_show_positional [private]
Definition at line 1857 of file cxxopts.hpp.
Referenced by help_one_group(), and show_positional_help().
m_tab_expansion
bool cxxopts::Options::m_tab_expansion [private]
Definition at line 1860 of file cxxopts.hpp.
Referenced by help_one_group(), and set_tab_expansion().
m_width
size_t cxxopts::Options::m_width [private]
Definition at line 1859 of file cxxopts.hpp.
Referenced by help_one_group(), and set_width().
The documentation for this class was generated from the following file:
src/core/utils/cxxopts.hpp