cxxopts::OptionParser Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionParser (const OptionMap &options, const PositionalList &positional, bool allow_unrecognised)
void add_to_option (OptionMap::const_iterator iter, const std::string &option, const std::string &arg)
void checked_parse_arg (int argc, const char *const *argv, int &current, const std::shared_ptr< OptionDetails > &value, const std::string &name)
bool consume_positional (const std::string &a, PositionalListIterator &next)
ParseResult parse (int argc, const char *const *argv)
void parse_default (const std::shared_ptr< OptionDetails > &details)
void parse_no_value (const std::shared_ptr< OptionDetails > &details)
void parse_option (const std::shared_ptr< OptionDetails > &value, const std::string &name, const std::string &arg=``)
Private Member Functions
void finalise_aliases ()
Private Attributes
bool m_allow_unrecognised
std::vector< KeyValue > m_defaults {}
NameHashMap m_keys {}
const OptionMap & m_options
ParsedHashMap m_parsed {}
const PositionalList & m_positional
std::vector< KeyValue > m_sequential {}
Detailed Description
Definition at line 1653 of file cxxopts.hpp.
Constructor & Destructor Documentation
OptionParser()
cxxopts::OptionParser::OptionParser (const OptionMap & options, const PositionalList & positional, bool allow_unrecognised) [inline]
Definition at line 1656 of file cxxopts.hpp.
                : m_options(options)
                , m_positional(positional)
                , m_allow_unrecognised(allow_unrecognised)
        {
        }
Member Function Documentation
add_to_option()
void cxxopts::OptionParser::add_to_option (OptionMap::const_iterator iter, const std::string & option, const std::string & arg) [inline]
Definition at line 2218 of file cxxopts.hpp.
    {
        parse_option(iter->second, option, arg);
    }
References parse_option().
Referenced by consume_positional().
checked_parse_arg()
void cxxopts::OptionParser::checked_parse_arg (int argc, const char *const * argv, int & current, const std::shared_ptr< OptionDetails > & value, const std::string & name) [inline]
Definition at line 2182 of file cxxopts.hpp.
    {
        if (current + 1 >= argc)
        {
            if (value->value().has_implicit())
            {
                parse_option(value, name, value->value().get_implicit_value());
            }
            else
            {
                throw_or_mimic<missing_argument_exception>(name);
            }
        }
        else
        {
            if (value->value().has_implicit())
            {
                parse_option(value, name, value->value().get_implicit_value());
            }
            else
            {
                parse_option(value, name, argv[current + 1]);
                ++current;
            }
        }
    }
References parse_option(), and cxxopts::value().
Referenced by parse().
consume_positional()
bool cxxopts::OptionParser::consume_positional (const std::string & a, PositionalListIterator & next) [inline]
Definition at line 2225 of file cxxopts.hpp.
    {
        while (next != m_positional.end())
        {
            auto iter = m_options.find(*next);
            if (iter != m_options.end())
            {
                if (!iter->second->value().is_container())
                {
                    auto& result = m_parsed[iter->second->hash()];
                    if (result.count() == 0)
                    {
                        add_to_option(iter, *next, a);
                        ++next;
                        return true;
                    }
                    ++next;
                    continue;
                }
                add_to_option(iter, *next, a);
                return true;
            }
            throw_or_mimic<option_not_exists_exception>(*next);
        }
        return false;
    }
References add_to_option(), m_options, m_parsed, and m_positional.
Referenced by parse().
finalise_aliases()
void cxxopts::OptionParser::finalise_aliases () [inline], [private]
Definition at line 2457 of file cxxopts.hpp.
    {
        for (auto& option: m_options)
        {
            auto& detail = *option.second;
            auto hash = detail.hash();
            m_keys[detail.short_name()] = hash;
            m_keys[detail.long_name()] = hash;
            m_parsed.emplace(hash, OptionValue());
        }
    }
References m_keys, m_options, and m_parsed.
Referenced by parse().
parse()
ParseResult cxxopts::OptionParser::parse (int argc, const char *const * argv) [inline]
Definition at line 2286 of file cxxopts.hpp.
    {
        int current = 1;
        bool consume_remaining = false;
        auto next_positional = m_positional.begin();
        std::vector<std::string> unmatched;
        while (current != argc)
        {
            if (strcmp(argv[current], "--") == 0)
            {
                consume_remaining = true;
                ++current;
                break;
            }
            bool matched = false;
            values::parser_tool::ArguDesc argu_desc =
                    values::parser_tool::ParseArgument(argv[current], matched);
            if (!matched)
            {
                //not a flag
                // but if it starts with a `-`, then it's an error
                if (argv[current][0] == '-' && argv[current][1] != '\0') {
                    if (!m_allow_unrecognised) {
                        throw_or_mimic<option_syntax_exception>(argv[current]);
                    }
                }
                //if true is returned here then it was consumed, otherwise it is
                //ignored
                if (consume_positional(argv[current], next_positional))
                {
                }
                else
                {
                    unmatched.emplace_back(argv[current]);
                }
                //if we return from here then it was parsed successfully, so continue
            }
            else
            {
                //short or long option?
                if (argu_desc.grouping)
                {
                    const std::string& s = argu_desc.arg_name;
                    for (size_t i = 0; i != s.size(); ++i)
                    {
                        std::string name(1, s[i]);
                        auto iter = m_options.find(name);
                        if (iter == m_options.end())
                        {
                            if (m_allow_unrecognised)
                            {
                                unmatched.push_back(std::string("-") + s[i]);
                                continue;
                            }
                            //error
                            throw_or_mimic<option_not_exists_exception>(name);
                        }
                        auto value = iter->second;
                        if (i + 1 == s.size())
                        {
                            //it must be the last argument
                            checked_parse_arg(argc, argv, current, value, name);
                        }
                        else if (value->value().has_implicit())
                        {
                            parse_option(value, name, value->value().get_implicit_value());
                        }
                        else if (i + 1 < s.size())
                        {
                            std::string arg_value = s.substr(i + 1);
                            parse_option(value, name, arg_value);
                            break;
                        }
                        else
                        {
                            //error
                            throw_or_mimic<option_requires_argument_exception>(name);
                        }
                    }
                }
                else if (argu_desc.arg_name.length() != 0)
                {
                    const std::string& name = argu_desc.arg_name;
                    auto iter = m_options.find(name);
                    if (iter == m_options.end())
                    {
                        if (m_allow_unrecognised)
                        {
                            // keep unrecognised options in argument list, skip to next argument
                            unmatched.emplace_back(argv[current]);
                            ++current;
                            continue;
                        }
                        //error
                        throw_or_mimic<option_not_exists_exception>(name);
                    }
                    auto opt = iter->second;
                    //equals provided for long option?
                    if (argu_desc.set_value)
                    {
                        //parse the option given
                        parse_option(opt, name, argu_desc.value);
                    }
                    else
                    {
                        //parse the next argument
                        checked_parse_arg(argc, argv, current, opt, name);
                    }
                }
            }
            ++current;
        }
        for (auto& opt : m_options)
        {
            auto& detail = opt.second;
            const auto& value = detail->value();
            auto& store = m_parsed[detail->hash()];
            if (value.has_default()) {
                if (!store.count() && !store.has_default()) {
                    parse_default(detail);
                }
            }
            else {
                parse_no_value(detail);
            }
        }
        if (consume_remaining)
        {
            while (current < argc)
            {
                if (!consume_positional(argv[current], next_positional)) {
                    break;
                }
                ++current;
            }
            //adjust argv for any that couldn't be swallowed
            while (current != argc) {
                unmatched.emplace_back(argv[current]);
                ++current;
            }
        }
        finalise_aliases();
        ParseResult parsed(std::move(m_keys), std::move(m_parsed), std::move(m_sequential), std::move(m_defaults), std::move(unmatched));
        return parsed;
    }
References cxxopts::values::parser_tool::ArguDesc::arg_name, checked_parse_arg(), consume_positional(), finalise_aliases(), cxxopts::values::parser_tool::ArguDesc::grouping, m_allow_unrecognised, m_defaults, m_keys, m_options, m_parsed, m_positional, m_sequential, parse_default(), parse_no_value(), parse_option(), cxxopts::values::parser_tool::ParseArgument(), cxxopts::values::parser_tool::ArguDesc::set_value, cxxopts::values::parser_tool::ArguDesc::value, and cxxopts::value().
Referenced by cxxopts::Options::parse().
parse_default()
void cxxopts::OptionParser::parse_default (const std::shared_ptr< OptionDetails > & details) [inline]
Definition at line 2148 of file cxxopts.hpp.
    {
        // TODO: remove the duplicate code here
        auto& store = m_parsed[details->hash()];
        store.parse_default(details);
        m_defaults.emplace_back(details->long_name(), details->value().get_default_value());
    }
References m_defaults, and m_parsed.
Referenced by parse().
parse_no_value()
void cxxopts::OptionParser::parse_no_value (const std::shared_ptr< OptionDetails > & details) [inline]
Definition at line 2158 of file cxxopts.hpp.
    {
        auto& store = m_parsed[details->hash()];
        store.parse_no_value(details);
    }
References m_parsed.
Referenced by parse().
parse_option()
void cxxopts::OptionParser::parse_option (const std::shared_ptr< OptionDetails > & value, const std::string & name, const std::string & arg = ``) [inline]
Definition at line 2166 of file cxxopts.hpp.
    {
        auto hash = value->hash();
        auto& result = m_parsed[hash];
        result.parse(value, arg);
        m_sequential.emplace_back(value->long_name(), arg);
    }
References m_parsed, m_sequential, and cxxopts::value().
Referenced by add_to_option(), checked_parse_arg(), and parse().
Member Data Documentation
m_allow_unrecognised
bool cxxopts::OptionParser::m_allow_unrecognised [private]
Definition at line 1705 of file cxxopts.hpp.
Referenced by parse().
m_defaults
std::vector<KeyValue> cxxopts::OptionParser::m_defaults {} [private]
Definition at line 1704 of file cxxopts.hpp.
Referenced by parse(), and parse_default().
m_keys
NameHashMap cxxopts::OptionParser::m_keys {} [private]
Definition at line 1708 of file cxxopts.hpp.
Referenced by finalise_aliases(), and parse().
m_options
const OptionMap& cxxopts::OptionParser::m_options [private]
Definition at line 1700 of file cxxopts.hpp.
Referenced by consume_positional(), finalise_aliases(), and parse().
m_parsed
ParsedHashMap cxxopts::OptionParser::m_parsed {} [private]
Definition at line 1707 of file cxxopts.hpp.
Referenced by consume_positional(), finalise_aliases(), parse(), parse_default(), parse_no_value(), and parse_option().
m_positional
const PositionalList& cxxopts::OptionParser::m_positional [private]
Definition at line 1701 of file cxxopts.hpp.
Referenced by consume_positional(), and parse().
m_sequential
std::vector<KeyValue> cxxopts::OptionParser::m_sequential {} [private]
Definition at line 1703 of file cxxopts.hpp.
Referenced by parse(), and parse_option().
The documentation for this class was generated from the following file:
src/core/utils/cxxopts.hpp